### ISSUE TITLE
Crash: Number of processes must be at least 1

### ISSUE THREAD

**Issue by joestringer** [cilium/cluster-diagnosis#63]
Reported by Andrew Howden on Slack, using sysdump tool downloaded from website in the last hour or so:

```
INFO collecting cilium gops stats ...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "cluster-diagnosis.zip/__main__.py", line 109, in <module>
  File "cluster-diagnosis.zip/sysdumpcollector.py", line 391, in collect
  File "cluster-diagnosis.zip/sysdumpcollector.py", line 142, in collect_gops_stats
  File "cluster-diagnosis.zip/sysdumpcollector.py", line 147, in collect_gops
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 732, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 154, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
```

**Comment by ruigulala** [comment]
Merged. Also updated the S3 bucket.
https://github.com/cilium/cluster-diagnosis/pull/64
