### ISSUE TITLE
Runtime exception: 'Namespace' object has no attribute 'cilium_labels'

### ISSUE THREAD

**Issue by joestringer** [cilium/cluster-diagnosis#69]
Reported in Slack:
https://cilium.slack.com/archives/C1MATJ5U5/p1572261217223400?thread_ts=1572259123.221800&cid=C1MATJ5U5

> I got the following error when running the cluster-diagnosis.zip 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "cluster-diagnosis.zip/__main__.py", line 97, in <module>
AttributeError: 'Namespace' object has no attribute 'cilium_labels'
```

**Comment by aanm** [comment]
It seems https://github.com/cilium/cluster-diagnosis/commit/77bb31aef5a2e707d2cea2e6f00d8872610eaca7 broke cluster-diagnosis
